
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIV FLOAT ID IGUAL INT LPAREN MULT NUMERO PUNTOCOMA RESTA RPAREN SUMAprograma : declaracion\n| asignacion\n| expresiondeclaracion : INT ID PUNTOCOMA\n| FLOAT ID PUNTOCOMAasignacion : ID IGUAL expresion PUNTOCOMAexpresion : expresion SUMA expresion\n| expresion RESTA expresion\n| expresion MULT expresion\n| expresion DIV expresionexpresion : LPAREN expresion RPARENexpresion : NUMEROexpresion : ID'
    
_lr_action_items = {'INT':([0,],[5,]),'FLOAT':([0,],[7,]),'ID':([0,5,7,8,10,11,12,13,15,],[6,14,16,18,18,18,18,18,18,]),'LPAREN':([0,8,10,11,12,13,15,],[8,8,8,8,8,8,8,]),'NUMERO':([0,8,10,11,12,13,15,],[9,9,9,9,9,9,9,]),'$end':([1,2,3,4,6,9,18,19,20,21,22,23,25,26,27,],[0,-1,-2,-3,-13,-12,-13,-7,-8,-9,-10,-4,-5,-11,-6,]),'SUMA':([4,6,9,17,18,19,20,21,22,24,26,],[10,-13,-12,10,-13,10,10,10,10,10,-11,]),'RESTA':([4,6,9,17,18,19,20,21,22,24,26,],[11,-13,-12,11,-13,11,11,11,11,11,-11,]),'MULT':([4,6,9,17,18,19,20,21,22,24,26,],[12,-13,-12,12,-13,12,12,12,12,12,-11,]),'DIV':([4,6,9,17,18,19,20,21,22,24,26,],[13,-13,-12,13,-13,13,13,13,13,13,-11,]),'IGUAL':([6,],[15,]),'RPAREN':([9,17,18,19,20,21,22,26,],[-12,26,-13,-7,-8,-9,-10,-11,]),'PUNTOCOMA':([9,14,16,18,19,20,21,22,24,26,],[-12,23,25,-13,-7,-8,-9,-10,27,-11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'declaracion':([0,],[2,]),'asignacion':([0,],[3,]),'expresion':([0,8,10,11,12,13,15,],[4,17,19,20,21,22,24,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> declaracion','programa',1,'p_programa','Analizador.py',75),
  ('programa -> asignacion','programa',1,'p_programa','Analizador.py',76),
  ('programa -> expresion','programa',1,'p_programa','Analizador.py',77),
  ('declaracion -> INT ID PUNTOCOMA','declaracion',3,'p_declaracion','Analizador.py',81),
  ('declaracion -> FLOAT ID PUNTOCOMA','declaracion',3,'p_declaracion','Analizador.py',82),
  ('asignacion -> ID IGUAL expresion PUNTOCOMA','asignacion',4,'p_asignacion','Analizador.py',98),
  ('expresion -> expresion SUMA expresion','expresion',3,'p_expresion_binaria','Analizador.py',118),
  ('expresion -> expresion RESTA expresion','expresion',3,'p_expresion_binaria','Analizador.py',119),
  ('expresion -> expresion MULT expresion','expresion',3,'p_expresion_binaria','Analizador.py',120),
  ('expresion -> expresion DIV expresion','expresion',3,'p_expresion_binaria','Analizador.py',121),
  ('expresion -> LPAREN expresion RPAREN','expresion',3,'p_expresion_parentesis','Analizador.py',137),
  ('expresion -> NUMERO','expresion',1,'p_expresion_numero','Analizador.py',141),
  ('expresion -> ID','expresion',1,'p_expresion_id','Analizador.py',145),
]
